/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.mail.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Identities implements java.io.Serializable {

	private static final long serialVersionUID = 7001993;

	private java.lang.Integer identityId;
	private java.lang.String  domainId;
	private java.lang.String  userId;
	private java.lang.String  email;
	private java.lang.String  displayName;
	private java.lang.String  mainFolder;
	private java.lang.Boolean fax;

	public Identities() {}

	public Identities(
		java.lang.Integer identityId,
		java.lang.String  domainId,
		java.lang.String  userId,
		java.lang.String  email,
		java.lang.String  displayName,
		java.lang.String  mainFolder,
		java.lang.Boolean fax
	) {
		this.identityId = identityId;
		this.domainId = domainId;
		this.userId = userId;
		this.email = email;
		this.displayName = displayName;
		this.mainFolder = mainFolder;
		this.fax = fax;
	}

	public java.lang.Integer getIdentityId() {
		return this.identityId;
	}

	public void setIdentityId(java.lang.Integer identityId) {
		this.identityId = identityId;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(java.lang.String displayName) {
		this.displayName = displayName;
	}

	public java.lang.String getMainFolder() {
		return this.mainFolder;
	}

	public void setMainFolder(java.lang.String mainFolder) {
		this.mainFolder = mainFolder;
	}

	public java.lang.Boolean getFax() {
		return this.fax;
	}

	public void setFax(java.lang.Boolean fax) {
		this.fax = fax;
	}
}
