/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.mail.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rules implements java.io.Serializable {

	private static final long serialVersionUID = 803119910;

	private java.lang.String     domainId;
	private java.lang.String     userId;
	private java.lang.Long       ruleId;
	private java.lang.String     status;
	private java.lang.String     continue_;
	private java.lang.String     keepCopy;
	private java.lang.String     condition;
	private java.lang.String     fromValue;
	private java.lang.String     toValue;
	private java.lang.String     subjectValue;
	private java.lang.String     sizeMatch;
	private java.math.BigInteger sizeValue;
	private java.lang.String     fieldName;
	private java.lang.String     fieldValue;
	private java.lang.String     action;
	private java.lang.String     actionValue;

	public Rules() {}

	public Rules(
		java.lang.String     domainId,
		java.lang.String     userId,
		java.lang.Long       ruleId,
		java.lang.String     status,
		java.lang.String     continue_,
		java.lang.String     keepCopy,
		java.lang.String     condition,
		java.lang.String     fromValue,
		java.lang.String     toValue,
		java.lang.String     subjectValue,
		java.lang.String     sizeMatch,
		java.math.BigInteger sizeValue,
		java.lang.String     fieldName,
		java.lang.String     fieldValue,
		java.lang.String     action,
		java.lang.String     actionValue
	) {
		this.domainId = domainId;
		this.userId = userId;
		this.ruleId = ruleId;
		this.status = status;
		this.continue_ = continue_;
		this.keepCopy = keepCopy;
		this.condition = condition;
		this.fromValue = fromValue;
		this.toValue = toValue;
		this.subjectValue = subjectValue;
		this.sizeMatch = sizeMatch;
		this.sizeValue = sizeValue;
		this.fieldName = fieldName;
		this.fieldValue = fieldValue;
		this.action = action;
		this.actionValue = actionValue;
	}

	public java.lang.String getDomainId() {
		return this.domainId;
	}

	public void setDomainId(java.lang.String domainId) {
		this.domainId = domainId;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.Long getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(java.lang.Long ruleId) {
		this.ruleId = ruleId;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getContinue() {
		return this.continue_;
	}

	public void setContinue(java.lang.String continue_) {
		this.continue_ = continue_;
	}

	public java.lang.String getKeepCopy() {
		return this.keepCopy;
	}

	public void setKeepCopy(java.lang.String keepCopy) {
		this.keepCopy = keepCopy;
	}

	public java.lang.String getCondition() {
		return this.condition;
	}

	public void setCondition(java.lang.String condition) {
		this.condition = condition;
	}

	public java.lang.String getFromValue() {
		return this.fromValue;
	}

	public void setFromValue(java.lang.String fromValue) {
		this.fromValue = fromValue;
	}

	public java.lang.String getToValue() {
		return this.toValue;
	}

	public void setToValue(java.lang.String toValue) {
		this.toValue = toValue;
	}

	public java.lang.String getSubjectValue() {
		return this.subjectValue;
	}

	public void setSubjectValue(java.lang.String subjectValue) {
		this.subjectValue = subjectValue;
	}

	public java.lang.String getSizeMatch() {
		return this.sizeMatch;
	}

	public void setSizeMatch(java.lang.String sizeMatch) {
		this.sizeMatch = sizeMatch;
	}

	public java.math.BigInteger getSizeValue() {
		return this.sizeValue;
	}

	public void setSizeValue(java.math.BigInteger sizeValue) {
		this.sizeValue = sizeValue;
	}

	public java.lang.String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(java.lang.String fieldName) {
		this.fieldName = fieldName;
	}

	public java.lang.String getFieldValue() {
		return this.fieldValue;
	}

	public void setFieldValue(java.lang.String fieldValue) {
		this.fieldValue = fieldValue;
	}

	public java.lang.String getAction() {
		return this.action;
	}

	public void setAction(java.lang.String action) {
		this.action = action;
	}

	public java.lang.String getActionValue() {
		return this.actionValue;
	}

	public void setActionValue(java.lang.String actionValue) {
		this.actionValue = actionValue;
	}
}
