/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.mail.jooq;

/**
 * Convenience access to all tables in mail
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table mail.autoresponders
	 */
	public static final com.sonicle.webtop.mail.jooq.tables.Autoresponders AUTORESPONDERS = com.sonicle.webtop.mail.jooq.tables.Autoresponders.AUTORESPONDERS;

	/**
	 * The table mail.identities
	 */
	public static final com.sonicle.webtop.mail.jooq.tables.Identities IDENTITIES = com.sonicle.webtop.mail.jooq.tables.Identities.IDENTITIES;

	/**
	 * The table mail.identities_old
	 */
	public static final com.sonicle.webtop.mail.jooq.tables.IdentitiesOld IDENTITIES_OLD = com.sonicle.webtop.mail.jooq.tables.IdentitiesOld.IDENTITIES_OLD;

	/**
	 * The table mail.in_filters
	 */
	public static final com.sonicle.webtop.mail.jooq.tables.InFilters IN_FILTERS = com.sonicle.webtop.mail.jooq.tables.InFilters.IN_FILTERS;

	/**
	 * The table mail.notes
	 */
	public static final com.sonicle.webtop.mail.jooq.tables.Notes NOTES = com.sonicle.webtop.mail.jooq.tables.Notes.NOTES;

	/**
	 * The table mail.rules
	 */
	public static final com.sonicle.webtop.mail.jooq.tables.Rules RULES = com.sonicle.webtop.mail.jooq.tables.Rules.RULES;

	/**
	 * The table mail.scan
	 */
	public static final com.sonicle.webtop.mail.jooq.tables.Scan SCAN = com.sonicle.webtop.mail.jooq.tables.Scan.SCAN;

	/**
	 * The table mail.users_map
	 */
	public static final com.sonicle.webtop.mail.jooq.tables.UsersMap USERS_MAP = com.sonicle.webtop.mail.jooq.tables.UsersMap.USERS_MAP;

	/**
	 * The table mail.vacation
	 */
	public static final com.sonicle.webtop.mail.jooq.tables.Vacation VACATION = com.sonicle.webtop.mail.jooq.tables.Vacation.VACATION;
}
