/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.mail.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _Rules_2eoldRecord extends org.jooq.impl.UpdatableRecordImpl<com.sonicle.webtop.mail.jooq.tables.records._Rules_2eoldRecord> implements org.jooq.Record16<java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1755119855;

	/**
	 * Setter for <code>mail._rules.old.domain_id</code>.
	 */
	public void setDomainId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>mail._rules.old.domain_id</code>.
	 */
	public java.lang.String getDomainId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>mail._rules.old.user_id</code>.
	 */
	public void setUserId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>mail._rules.old.user_id</code>.
	 */
	public java.lang.String getUserId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>mail._rules.old.rule_id</code>.
	 */
	public void setRuleId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>mail._rules.old.rule_id</code>.
	 */
	public java.lang.Long getRuleId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>mail._rules.old.status</code>.
	 */
	public void setStatus(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>mail._rules.old.status</code>.
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>mail._rules.old.continue</code>.
	 */
	public void setContinue(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>mail._rules.old.continue</code>.
	 */
	public java.lang.String getContinue() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>mail._rules.old.keep_copy</code>.
	 */
	public void setKeepCopy(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>mail._rules.old.keep_copy</code>.
	 */
	public java.lang.String getKeepCopy() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>mail._rules.old.condition</code>.
	 */
	public void setCondition(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>mail._rules.old.condition</code>.
	 */
	public java.lang.String getCondition() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>mail._rules.old.from_value</code>.
	 */
	public void setFromValue(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>mail._rules.old.from_value</code>.
	 */
	public java.lang.String getFromValue() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>mail._rules.old.to_value</code>.
	 */
	public void setToValue(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>mail._rules.old.to_value</code>.
	 */
	public java.lang.String getToValue() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>mail._rules.old.subject_value</code>.
	 */
	public void setSubjectValue(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>mail._rules.old.subject_value</code>.
	 */
	public java.lang.String getSubjectValue() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>mail._rules.old.size_match</code>.
	 */
	public void setSizeMatch(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>mail._rules.old.size_match</code>.
	 */
	public java.lang.String getSizeMatch() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>mail._rules.old.size_value</code>.
	 */
	public void setSizeValue(java.math.BigInteger value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>mail._rules.old.size_value</code>.
	 */
	public java.math.BigInteger getSizeValue() {
		return (java.math.BigInteger) getValue(11);
	}

	/**
	 * Setter for <code>mail._rules.old.field_name</code>.
	 */
	public void setFieldName(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>mail._rules.old.field_name</code>.
	 */
	public java.lang.String getFieldName() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>mail._rules.old.field_value</code>.
	 */
	public void setFieldValue(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>mail._rules.old.field_value</code>.
	 */
	public java.lang.String getFieldValue() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>mail._rules.old.action</code>.
	 */
	public void setAction(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>mail._rules.old.action</code>.
	 */
	public java.lang.String getAction() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>mail._rules.old.action_value</code>.
	 */
	public void setActionValue(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>mail._rules.old.action_value</code>.
	 */
	public java.lang.String getActionValue() {
		return (java.lang.String) getValue(15);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record3<java.lang.String, java.lang.String, java.lang.Long> key() {
		return (org.jooq.Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record16 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row16<java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row16) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row16<java.lang.String, java.lang.String, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.math.BigInteger, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row16) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.DOMAIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.RULE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.CONTINUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.KEEP_COPY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.CONDITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.FROM_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.TO_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.SUBJECT_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.SIZE_MATCH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigInteger> field12() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.SIZE_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.FIELD_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.FIELD_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.ACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field16() {
		return com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD.ACTION_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getDomainId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getRuleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getContinue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getKeepCopy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getCondition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getFromValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getToValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getSubjectValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getSizeMatch();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigInteger value12() {
		return getSizeValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getFieldName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getFieldValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getAction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value16() {
		return getActionValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value1(java.lang.String value) {
		setDomainId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value2(java.lang.String value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value3(java.lang.Long value) {
		setRuleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value4(java.lang.String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value5(java.lang.String value) {
		setContinue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value6(java.lang.String value) {
		setKeepCopy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value7(java.lang.String value) {
		setCondition(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value8(java.lang.String value) {
		setFromValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value9(java.lang.String value) {
		setToValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value10(java.lang.String value) {
		setSubjectValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value11(java.lang.String value) {
		setSizeMatch(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value12(java.math.BigInteger value) {
		setSizeValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value13(java.lang.String value) {
		setFieldName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value14(java.lang.String value) {
		setFieldValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value15(java.lang.String value) {
		setAction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord value16(java.lang.String value) {
		setActionValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public _Rules_2eoldRecord values(java.lang.String value1, java.lang.String value2, java.lang.Long value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, java.lang.String value11, java.math.BigInteger value12, java.lang.String value13, java.lang.String value14, java.lang.String value15, java.lang.String value16) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached _Rules_2eoldRecord
	 */
	public _Rules_2eoldRecord() {
		super(com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD);
	}

	/**
	 * Create a detached, initialised _Rules_2eoldRecord
	 */
	public _Rules_2eoldRecord(java.lang.String domainId, java.lang.String userId, java.lang.Long ruleId, java.lang.String status, java.lang.String continue_, java.lang.String keepCopy, java.lang.String condition, java.lang.String fromValue, java.lang.String toValue, java.lang.String subjectValue, java.lang.String sizeMatch, java.math.BigInteger sizeValue, java.lang.String fieldName, java.lang.String fieldValue, java.lang.String action, java.lang.String actionValue) {
		super(com.sonicle.webtop.mail.jooq.tables._Rules_2eold._RULES_2eOLD);

		setValue(0, domainId);
		setValue(1, userId);
		setValue(2, ruleId);
		setValue(3, status);
		setValue(4, continue_);
		setValue(5, keepCopy);
		setValue(6, condition);
		setValue(7, fromValue);
		setValue(8, toValue);
		setValue(9, subjectValue);
		setValue(10, sizeMatch);
		setValue(11, sizeValue);
		setValue(12, fieldName);
		setValue(13, fieldValue);
		setValue(14, action);
		setValue(15, actionValue);
	}
}
