/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.mail.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Autoresponders extends org.jooq.impl.TableImpl<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord> {

	private static final long serialVersionUID = -1796745394;

	/**
	 * The reference instance of <code>mail.autoresponders</code>
	 */
	public static final com.sonicle.webtop.mail.jooq.tables.Autoresponders AUTORESPONDERS = new com.sonicle.webtop.mail.jooq.tables.Autoresponders();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord> getRecordType() {
		return com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord.class;
	}

	/**
	 * The column <code>mail.autoresponders.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>mail.autoresponders.user_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>mail.autoresponders.enabled</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord, java.lang.Boolean> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mail.autoresponders.subject</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord, java.lang.String> SUBJECT = createField("subject", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>mail.autoresponders.message</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord, java.lang.String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * The column <code>mail.autoresponders.addresses</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord, java.lang.String> ADDRESSES = createField("addresses", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * The column <code>mail.autoresponders.days_interval</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord, java.lang.Short> DAYS_INTERVAL = createField("days_interval", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mail.autoresponders.start_date</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord, org.joda.time.DateTime> START_DATE = createField("start_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new com.sonicle.webtop.core.jooq.DateTimeConverter());

	/**
	 * The column <code>mail.autoresponders.end_date</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord, org.joda.time.DateTime> END_DATE = createField("end_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "", new com.sonicle.webtop.core.jooq.DateTimeConverter());

	/**
	 * The column <code>mail.autoresponders.skip_mailing_lists</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord, java.lang.Boolean> SKIP_MAILING_LISTS = createField("skip_mailing_lists", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>mail.autoresponders</code> table reference
	 */
	public Autoresponders() {
		this("autoresponders", null);
	}

	/**
	 * Create an aliased <code>mail.autoresponders</code> table reference
	 */
	public Autoresponders(java.lang.String alias) {
		this(alias, com.sonicle.webtop.mail.jooq.tables.Autoresponders.AUTORESPONDERS);
	}

	private Autoresponders(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Autoresponders(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.mail.jooq.Mail.MAIL, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord> getPrimaryKey() {
		return com.sonicle.webtop.mail.jooq.Keys.AUTORESPONDER_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.mail.jooq.tables.records.AutorespondersRecord>>asList(com.sonicle.webtop.mail.jooq.Keys.AUTORESPONDER_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.mail.jooq.tables.Autoresponders as(java.lang.String alias) {
		return new com.sonicle.webtop.mail.jooq.tables.Autoresponders(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.mail.jooq.tables.Autoresponders rename(java.lang.String name) {
		return new com.sonicle.webtop.mail.jooq.tables.Autoresponders(name, null);
	}
}
