/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.mail.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notes extends org.jooq.impl.TableImpl<com.sonicle.webtop.mail.jooq.tables.records.NotesRecord> {

	private static final long serialVersionUID = 1956523266;

	/**
	 * The reference instance of <code>mail.notes</code>
	 */
	public static final com.sonicle.webtop.mail.jooq.tables.Notes NOTES = new com.sonicle.webtop.mail.jooq.tables.Notes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.mail.jooq.tables.records.NotesRecord> getRecordType() {
		return com.sonicle.webtop.mail.jooq.tables.records.NotesRecord.class;
	}

	/**
	 * The column <code>mail.notes.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.NotesRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>mail.notes.message_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.NotesRecord, java.lang.String> MESSAGE_ID = createField("message_id", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>mail.notes.text</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.NotesRecord, java.lang.String> TEXT = createField("text", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>mail.notes</code> table reference
	 */
	public Notes() {
		this("notes", null);
	}

	/**
	 * Create an aliased <code>mail.notes</code> table reference
	 */
	public Notes(java.lang.String alias) {
		this(alias, com.sonicle.webtop.mail.jooq.tables.Notes.NOTES);
	}

	private Notes(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.mail.jooq.tables.records.NotesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Notes(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.mail.jooq.tables.records.NotesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.mail.jooq.Mail.MAIL, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.mail.jooq.tables.records.NotesRecord> getPrimaryKey() {
		return com.sonicle.webtop.mail.jooq.Keys.NOTES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.mail.jooq.tables.records.NotesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.mail.jooq.tables.records.NotesRecord>>asList(com.sonicle.webtop.mail.jooq.Keys.NOTES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.mail.jooq.tables.Notes as(java.lang.String alias) {
		return new com.sonicle.webtop.mail.jooq.tables.Notes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.mail.jooq.tables.Notes rename(java.lang.String name) {
		return new com.sonicle.webtop.mail.jooq.tables.Notes(name, null);
	}
}
