/**
 * This class is generated by jOOQ
 */
package com.sonicle.webtop.mail.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rules extends org.jooq.impl.TableImpl<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord> {

	private static final long serialVersionUID = -751210955;

	/**
	 * The reference instance of <code>mail.rules</code>
	 */
	public static final com.sonicle.webtop.mail.jooq.tables.Rules RULES = new com.sonicle.webtop.mail.jooq.tables.Rules();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord> getRecordType() {
		return com.sonicle.webtop.mail.jooq.tables.records.RulesRecord.class;
	}

	/**
	 * The column <code>mail.rules.domain_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.String> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>mail.rules.user_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>mail.rules.rule_id</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.Long> RULE_ID = createField("rule_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>mail.rules.status</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>mail.rules.continue</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.String> CONTINUE = createField("continue", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>mail.rules.keep_copy</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.String> KEEP_COPY = createField("keep_copy", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>mail.rules.condition</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.String> CONDITION = createField("condition", org.jooq.impl.SQLDataType.VARCHAR.length(3).nullable(false), this, "");

	/**
	 * The column <code>mail.rules.from_value</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.String> FROM_VALUE = createField("from_value", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * The column <code>mail.rules.to_value</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.String> TO_VALUE = createField("to_value", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * The column <code>mail.rules.subject_value</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.String> SUBJECT_VALUE = createField("subject_value", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * The column <code>mail.rules.size_match</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.String> SIZE_MATCH = createField("size_match", org.jooq.impl.SQLDataType.VARCHAR.length(1), this, "");

	/**
	 * The column <code>mail.rules.size_value</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.math.BigInteger> SIZE_VALUE = createField("size_value", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38), this, "");

	/**
	 * The column <code>mail.rules.field_name</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.String> FIELD_NAME = createField("field_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>mail.rules.field_value</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.String> FIELD_VALUE = createField("field_value", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * The column <code>mail.rules.action</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.String> ACTION = createField("action", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * The column <code>mail.rules.action_value</code>.
	 */
	public final org.jooq.TableField<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord, java.lang.String> ACTION_VALUE = createField("action_value", org.jooq.impl.SQLDataType.VARCHAR.length(4000), this, "");

	/**
	 * Create a <code>mail.rules</code> table reference
	 */
	public Rules() {
		this("rules", null);
	}

	/**
	 * Create an aliased <code>mail.rules</code> table reference
	 */
	public Rules(java.lang.String alias) {
		this(alias, com.sonicle.webtop.mail.jooq.tables.Rules.RULES);
	}

	private Rules(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Rules(java.lang.String alias, org.jooq.Table<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.sonicle.webtop.mail.jooq.Mail.MAIL, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord> getPrimaryKey() {
		return com.sonicle.webtop.mail.jooq.Keys.FILTERS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.sonicle.webtop.mail.jooq.tables.records.RulesRecord>>asList(com.sonicle.webtop.mail.jooq.Keys.FILTERS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.sonicle.webtop.mail.jooq.tables.Rules as(java.lang.String alias) {
		return new com.sonicle.webtop.mail.jooq.tables.Rules(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.sonicle.webtop.mail.jooq.tables.Rules rename(java.lang.String name) {
		return new com.sonicle.webtop.mail.jooq.tables.Rules(name, null);
	}
}
